// Generated by https://quicktype.io

import { User } from "src/app/domain/models/user.model";

export interface UserDto {
    page:        number;
    per_page:    number;
    total:       number;
    total_pages: number;
    data:        Datum[];
    support:     Support;
}

export interface Datum {
    id:         number;
    email:      string;
    first_name: string;
    last_name:  string;
    avatar:     string;
}

export interface Support {
    url:  string;
    text: string;
}


export class UserDtoTransformer {
    constructor() {}

    transform(dto: UserDto): User[] {
        const listUser: User[] = dto.data.map(u => {
            const user: User = new User();
            user.id = u.id.toString();
            user.firstName = u.first_name;
            user.lastName = u.last_name,
            user.email = u.email,
            user.avatarUrl = u.avatar
            return user;
        });
        return listUser;
        
    }
}
